[mypy]
python_version = 3.13
strict = False
plugins = pydantic.mypy
mypy_path = src
explicit_package_bases = True

# Stub management
mypy_path = src:stubs

# Ignore missing imports for the project and libraries
[mypy-sota_dl.*]
ignore_missing_imports = True

[mypy-yt_dlp.*]
ignore_missing_imports = True

[mypy-psutil.*]
ignore_missing_imports = True

[mypy-cryptography.*]
ignore_missing_imports = True

