[mypy]
python_version = 3.13
strict = True
plugins = pydantic.mypy
mypy_path = src
explicit_package_bases = True

# Stub management
mypy_path = src:stubs

# Maximum 'Any' restriction rules
disallow_any_unimported = True
disallow_any_decorated = True
disallow_any_explicit = True
disallow_any_expr = True
disallow_any_generics = True
disallow_subtyped_by_any = True

