[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sota-downloader"
version = "1.0.0"
description = "A modular, terminal-based media extraction tool optimized for Android/Termux."
requires-python = ">=3.10"
dependencies = [
    "yt-dlp>=2026.07.04",
    "rich>=13.7.1",
    "mutagen>=1.47.0"
]

[project.scripts]
sota = "main:main_menu"

[tool.setuptools]
packages = ["config", "core", "ui", "utils"]
py-modules = ["main"]

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
