[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sota-downloader"
version = "3.0.1"
description = "A modular, terminal-based media extraction tool optimized for Android/Termux."
requires-python = ">=3.10"
dependencies = [
    "yt-dlp>=2026.07.04",
    "rich>=13.7.1",
    "mutagen>=1.47.0",
    "pydantic>=2.8.2",
    "tenacity>=8.5.0",
    "requests>=2.32.3"
]

[project.scripts]
sota = "sota_dl.main:main_menu"

[tool.setuptools.packages.find]
where = ["src"]
include = ["sota_dl*"]

[tool.setuptools]
py-modules = ["sota_dl.main"]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "S"]
ignore = []

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["S101"]
"ui/menus.py" = ["S608"]

[tool.mypy]
python_version = "3.10"
strict = true

[[tool.mypy.overrides]]
module = [
    "psutil",
    "yt_dlp",
    "yt_dlp.utils",
    "pywidevine.*",
    "video_download_drm",
    "browser_cookie3"
]
ignore_missing_imports = true
